### PR TITLE
New vision models

### PR DESCRIPTION
**Pull request by Cdk29**
Here the news models.

I have tried some locally, it works fine _a priori._

I took the freedom to rearrange a bit the order of inside R/vision_models.R to see more easily what was missing from https://docs.fast.ai/vision.models.xresnet.html. It will ease the long term maintenance too I think.

### CODE REVIEW

**Comment by Cdk29** [comment]
I don't know why there is older commits coming with it. I managed to create a merging conflic with a pyc dependencies that I had to merged.

**Comment by henry090** [comment]
@Cdk29 Could you create a new branch and PR from there, please?

**Comment by Cdk29** [comment]
@henry090 it does the same, the old commit came with it, it seems to be the normal yet weird behavior of github. 

The files where the previous commit took place remains unchanged.

**Comment by henry090** [comment]
Thanks! Please, open a new branch for new PRs =)

**Comment by Cdk29** [comment]
@henry090 haha okay I will !

**Pull request merged**
