### PR TITLE
Xla

### PR DESCRIPTION
**Pull request by henry090**
@Cdk29 I added this to fastai. Could you check if we covered all the steps for TPU?

### CODE REVIEW

**Comment by Cdk29** [comment]
@henry090 I will check but I will first need to set up something on google colab right?

**Comment by henry090** [comment]
@Cdk29 This is how I set up R notebook https://colab.research.google.com/drive/1Wf9aTdcC_YtigjQIYcG8zJqq2q_vpZR9?usp=sharing

**Comment by Cdk29** [comment]
Okay when I can I look into this.

**Comment by henry090** [comment]
Github team updated Mac os, therefore it fails: https://github.com/actions/virtual-environments
https://github.com/actions/virtual-environments/pull/2535

**Comment by henry090** [comment]
@Cdk29 I am merging this, later I will try to run PETS dataset on Colab to see if this will work on TPUs

**Pull request merged**
